config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :products do
    resources :reviews, only: [:show, :create, :destroy]

    member do
      get 'add_to_cart', to: "products#add_to_cart"
      post 'add_to_button', to: "products#add_to_button"
    end

    collection do
      post 'button_order', to: "products#button_order"
    end
  end

  get '/users/products', to: 'users#user_products'

  resources :users do
    resources :buttons do
      member do
        get 'products', to: 'buttons#products'
      end

      collection do
        get 'login', to: 'buttons#login'
        post 'authenticate', to: 'buttons#authenticate'
        get 'logout', to: 'buttons#logout'
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :cart_items, only: :destroy

  resources :cart, only: :index do
    collection do
      get 'checkout', to: 'cart#checkout'
      get 'order', to: 'cart#order'
      get 'delete', to: 'cart#delete'
    end
  end

end

app/models/button.rb
class Button < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

end

app/controllers/buttons_controller.rb
class ButtonsController < ApplicationController
  before_action :ensure_logged_in

  def index
    @access_token = access_token
    @my_buttons = HTTParty.get('https://api.particle.io/v1/devices', query: {access_token: @access_token})
  end

  def products
    @products = Product.where.not(seller: current_user).order(created_at: :desc)
  end

  def login
  end

  def authenticate
    params.except!(:utf8, :authenticity_token, :commit, :controller, :action)
    @@access_token = HTTParty.post('https://api.particle.io/oauth/token', body: params)["access_token"]

    if @@access_token == nil
      redirect_to user_buttons_url, alert: "Username or password was incorrect. Please try again."
    else
      redirect_to user_buttons_url
    end
  end

  def create
    @button = current_user.buttons.build(core_id: params[:core_id], access_token: @@access_token)

    if @button.save
      redirect_to user_buttons_url, notice: "Button added successfully"
    else
      render user_buttons_url, alert: "An error occurred"
    end
  end

  def logout
    @@access_token = nil
    redirect_to user_buttons_url
  end

  private
  def access_token
    @@access_token ||= nil
  end

  def registered?(id)
    Button.exists?(core_id: id)
  end
end

app/helpers/buttons_helper.rb
module ButtonsHelper
  def not_authenticated?(token)
    token.nil?
  end

  def get_button(button)
    Button.find_by(core_id: button["id"])
  end
end

app/views/buttons/index.html.erb
<h1>My Rainforest Dash Buttons</h1>

<% if not_authenticated? @access_token %>

  <%= link_to "Sign in to your Particle IO account", login_user_buttons_path %>

<% else %>

  <%= link_to "Save Buttons", logout_user_buttons_path %>

  <% @my_buttons.each do |button| %>
    <div>
      <p>Name: <%= button["name"] %></p> <br>

      <% unless registered? button["id"] %>

        <%= form_tag user_buttons_path do %>
          <%= hidden_field_tag :core_id, button["id"] %>
          <%= submit_tag "Add" %>
        <% end %>

      <% else %>
        <% button = get_button(button) %>
        <% if button.product.nil? %>
          <%= link_to "Tag it to a product!", products_user_button_path(current_user, button) %>
        <% else %>
          <%= link_to "Go to product", product_path(button.product) %>
        <% end %>
      <% end %>

    </div>
  <% end %>

<% end %>

app/views/buttons/login.html.erb
<h1>My Rainforest Dash Buttons</h1>

<%= form_tag authenticate_user_buttons_path do %>

  <%= hidden_field_tag :client_id, 'spark' %>
  <%= hidden_field_tag :client_secret, 'spark' %>
  <%= hidden_field_tag :grant_type, 'password' %>

  <div>
    <%= label_tag :username %> <br>
    <%= text_field_tag :username %>
  </div>

  <div>
    <%= label_tag :password %> <br>
    <%= password_field_tag :password %>
  </div>

  <div>
    <%= submit_tag %>
  </div>

<% end %>

app/views/buttons/products.html.erb
<h1>Products</h1>
<%= link_to "Back", login_user_buttons_path %>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @products.each_slice(3) do |products| %>
    <tr>
      <% products.each do |product| %>
        <td style="padding: 30px">
          <p>Name: <%= product.name %></p>
          <p>Price: $ <%= product.formatted_price %></p>
          <p>Description: <%= product.description %></p>
          <%= form_tag add_to_button_product_path do %>
            <%= hidden_field_tag :product_id, product.id %>
            <%= submit_tag "Tag" %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>