config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :products do
    resources :reviews, only: [:show, :create, :destroy]

    member do
      get 'add_to_cart', to: "products#add_to_cart"
      post 'add_to_button', to: "products#add_to_button"
    end

    collection do
      post 'button_order', to: "products#button_order"
    end
  end

  get '/users/products', to: 'users#user_products'

  resources :users do
    resources :buttons do
      member do
        get 'products', to: 'buttons#products'
      end

      collection do
        get 'login', to: 'buttons#login'
        post 'authenticate', to: 'buttons#authenticate'
        get 'logout', to: 'buttons#logout'
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :cart_items, only: :destroy

  resources :cart, only: :index do
    collection do
      get 'checkout', to: 'cart#checkout'
      get 'order', to: 'cart#order'
      get 'delete', to: 'cart#delete'
    end
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :ensure_logged_in
  before_action :get_cart

  def index
  end

  def checkout
  end

  def delete
    remove_all
    redirect_to cart_index_path
  end

  def order
    remove_all
    redirect_to cart_index_path, notice: "Order has been shipped."
  end

  private
  def get_cart
    @cart_items = current_user.cart.all
  end

  def remove_all
    @cart_items.each { |item| item.destroy }
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/cart/_cart_items.html.erb
<table>
  <tr>
    <th style="width: 300px"></th>
    <th style="width: 100px"></th>
    <th style-"width: 100px"></th>
  </tr>
  <% @cart_items.each do |item| %>
    <tr>
      <td><p><%= item.product.name %></p></td>
      <td><p>$ <%= item.formatted_price %></p></td>
      <td><%= link_to "Remove", cart_item_path(item), method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
    <tr><td colspan="2" style="border-top: 1pt black solid"></td></tr>
    <tr>
      <td><p>Subtotal:</p></td>
      <td><p>$ <%= subtotal = calculate(@cart_items, :unit_price) %></p></td>
      <td><p><%= link_to "Remove all", delete_cart_index_path, data: { confirm: "Are you sure?" } %> || <%= link_to "Checkout", checkout_cart_index_path %></p></td>
    </tr>
</table>

app/views/cart/_order_summary.html.erb
<table>
  <tr>
    <th style="width: 300px"></th>
    <th style="width: 100px"></th>
    <th style-"width: 100px"></th>
  </tr>
  <% @cart_items.each do |item| %>
    <tr>
      <td><p><%= item.product.name %></p></td>
      <td><p>$ <%= item.unit_price %></p></td>
    </tr>
  <% end %>
  <tr><td colspan="2" style="border-top: 1pt black solid"></td></tr>
  <tr>
    <td><p>Subtotal:</p></td>
    <td><p>$ <%= subtotal = calculate(@cart_items, :unit_price) %></p></td>
  </tr>
  <tr>
    <td><p>Tax:</p></td>
    <td><p>$ <%= tax = calculate(@cart_items, :tax) %></p></td>
  </tr>
  <tr>
    <td><p>Total:</p></td>
    <td><p>$ <%= sprintf('%.2f', subtotal.to_f + tax.to_f) %></p></td>
  </tr>
  <tr>
    <td></td>
    <td><p><%= link_to "Submit Order", order_cart_index_path %></p></td>
  </tr>
</table>

app/views/cart/checkout.html.erb
<h1>Order Summary</h1>

<%= render "order_summary" %>

app/views/cart/index.html.erb
<h1>My Cart</h1>

<% if @cart_items.any? %>
  <%= render "cart_items" %>
<% else %>
  <p>There are no items in your cart.</p>
<% end %>