config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :products do
    resources :reviews, only: [:show, :create, :destroy]

    member do
      get 'add_to_cart', to: "products#add_to_cart"
      post 'add_to_button', to: "products#add_to_button"
    end

    collection do
      post 'button_order', to: "products#button_order"
    end
  end

  get '/users/products', to: 'users#user_products'

  resources :users do
    resources :buttons do
      member do
        get 'products', to: 'buttons#products'
      end

      collection do
        get 'login', to: 'buttons#login'
        post 'authenticate', to: 'buttons#authenticate'
        get 'logout', to: 'buttons#logout'
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :cart_items, only: :destroy

  resources :cart, only: :index do
    collection do
      get 'checkout', to: 'cart#checkout'
      get 'order', to: 'cart#order'
      get 'delete', to: 'cart#delete'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  has_many :products, through: :reviews

  has_many :merchandise, class_name: "Product", foreign_key: "seller_id", dependent: :destroy

  has_many :buttons, dependent: :destroy
  has_many :orders, through: :buttons, source: :product

  has_many :cart_items, dependent: :destroy do
    def add(product)
      cart_item = new(product: product)
      cart_item.unit_price = product.price
      cart_item.save
      cart_item
    end
  end
  alias_method :cart, :cart_items

  validates :first_name, :last_name, :username, :email, presence: true
  validates :username, :email, uniqueness: { message: "is already in use" }

  has_secure_password

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_current_user, except: [:new, :create]
  before_action :ensure_logged_out, only: :new
  before_action :ensure_logged_in, except: [:new, :create]

  def index
  end

  def user_products
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to products_url, notice: "Sign up successful!"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @seller.update_attributes(user_params)
      redirect_to user_url(@seller)
    else
      render :edit
    end
  end

  def destroy
    @seller.destroy
    session[:user_id] = nil
    redirect_to products_url
  end

  private
  def get_current_user
    @seller = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Hi, <%= @seller.first_name %></h1>

<%= link_to "My Products", users_products_path %> <br>
<%= link_to "My Buttons", user_buttons_path(@seller) %> <br>
<%= link_to "User Settings", user_path(@seller) %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <h2>Couldn't create user due to <%= pluralize(@user.errors.count, "error") %>:</h2>

    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

    <div>
    <%= f.label :first_name, "First Name" %> <br>
    <%= f.text_field :first_name %>
  </div>

    <div>
    <%= f.label :last_name, "Last Name" %> <br>
    <%= f.text_field :last_name %>
  </div>

    <div>
    <%= f.label :username %> <br>
    <%= f.text_field :username %>
  </div>

  <div>
    <%= f.label :email %> <br>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %> <br>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation, "Confirm Password" %> <br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
  <%= f.submit "Create Account" %>
  </div>

<% end %>

<!-- <br><%= link_to "Back Home", products_path %> -->

<!-- Bug: Goes to immediate back page with ':back' -->

app/views/users/show.html.erb
<h1>User Settings</h1>

<%= link_to "Back", users_path %>

<div>
  <p>Name: <%= @seller.first_name %> <%= @seller.last_name %></p>
</div>

<div>
  <p>Username: <%= @seller.username %></p>
</div>

<div>
  <p>Email: <%= @seller.email %></p>
</div>

<div>
  <p><%= link_to "Delete Account", user_path(@seller), style: "color: red", method: :delete, data: {confirm: 'Are you sure?'} %></p>
</div>

app/views/users/user_products.html.erb
<h1>My Products</h1>

<%= link_to "Back", users_path %>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @seller.merchandise.each_slice(3) do |merchandises| %>
    <tr>
      <% merchandises.each do |merchandise| %>
        <td style="padding: 30px">
          <p>Name: <%= merchandise.name %></p>
          <p>Price: $ <%= merchandise.formatted_price %></p>
          <p>Description: <%= merchandise.description %></p>
          <%= link_to "Details", product_path(merchandise) %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>