config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :products do
    resources :reviews, only: [:show, :create, :destroy]

    member do
      get 'add_to_cart', to: "products#add_to_cart"
      post 'add_to_button', to: "products#add_to_button"
    end

    collection do
      post 'button_order', to: "products#button_order"
    end
  end

  get '/users/products', to: 'users#user_products'

  resources :users do
    resources :buttons do
      member do
        get 'products', to: 'buttons#products'
      end

      collection do
        get 'login', to: 'buttons#login'
        post 'authenticate', to: 'buttons#authenticate'
        get 'logout', to: 'buttons#logout'
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :cart_items, only: :destroy

  resources :cart, only: :index do
    collection do
      get 'checkout', to: 'cart#checkout'
      get 'order', to: 'cart#order'
      get 'delete', to: 'cart#delete'
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews

  belongs_to :seller, class_name: "User"
  has_many :cart_items

  has_many :buttons, dependent: :destroy
  has_many :customers, through: :buttons, source: :user

  validates :description, :name, presence: true
  validates :price, format: { with: /\A[+]?(\d+|\d+\.\d{1,2})\Z/, message: "is in the wrong format [ $ 0.00 ]" }

  def formatted_price
    sprintf("%.2f", price)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :get_product, only: [:show, :add_to_cart, :update, :destroy]
  before_action :ensure_logged_in, only: [:new, :add_to_cart]

  def index
    clear_path

    @products = Product.all
    @products = @products.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%") if params[:search]
    @products = @products.page(params[:page])

    # respond_to do |format|
    #   format.html do
    #     if request.xhr?
    #       render @products
    #     else
    #       render :index
    #     end
    #   end

    #   format.js do
    #     render :index
    #   end
    # end

    # refactored from above to
    respond_to do |format|
      format.html { render :index }
      format.js {}
    end
  end

  def show
    @review = Review.new(product: @product)
    @reviews = @product.reviews.order(created_at: :asc)
  end

  def add_to_cart
    if !current_user.merchandise.exists?(@product)
      if !in_cart(@product)
        @cart_item = current_user.cart.add(@product)
        redirect_to product_path(@product), notice: "#{ @product.name } was added to your cart."
      else
        redirect_to product_path(@product), alert: "#{ @product.name } already exists in your cart."
      end
    end
  end

  def add_to_button
    button = Button.find(params[:id])
    button.update_attributes(product_id: params[:product_id])
    redirect_to login_user_buttons_url(current_user), notice: "Button was tagged successfully"
  end

  def button_order
    button = Button.find_by(core_id: params[:core_id])
    core = RubySpark::Core.new(button.core_id, button.access_token)

    if core
      user = User.find(button.user_id)
      product = Product.find(button.product_id)
      user.cart.add(product)

      core.function("cartResponse", "success")
    else
      core.function("cartResponse", "error")
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.merchandise.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def edit
    if authorized(current_user)
      get_product
    else
      redirect_to products_url
    end
  end

  def update
    if @product.update_attributes(product_params)
      redirect_to product_url(@product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url
  end

  private
  def authorized(user)
    user == Product.find(params[:id]).user
  end

  def get_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price)
  end

  def in_cart(item)
    current_user.cart.exists?(product_id: item.id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :price %> <br>
    <%= f.text_field :price %>
  </div>

  <div>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>
  </div>

  <%= f.submit %>

<% end %>

app/views/products/_product.html.erb
<% if product_counter != 0 && product_counter % 3 == 0 %>
  </tr>
  <tr>
    <td style="padding: 30px">
      <p>Name: <%= product.name %></p>
      <p>Price: $ <%= product.formatted_price %></p>
      <p>Description: <%= product.description %></p>
      <%= link_to "Details", product_path(product) %>
    </td>
<% else %>
  <td style="padding: 30px">
    <p>Name: <%= product.name %></p>
    <p>Price: $ <%= product.formatted_price %></p>
    <p>Description: <%= product.description %></p>
    <%= link_to "Details", product_path(product) %>
  </td>
<% end %>

app/views/products/_review_form.html.erb
<h4>New Review</h4>

<%= form_for [@product, @review], remote: true do |f| %>
  <% if @review.errors.any? %>
    <h4>Couldn't create user due to <%= pluralize(@user.errors.count, "error") %>:</h4>

    <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :comment %> <br>
    <%= f.text_area :comment %>
  </div>

  <%= f.submit "Upload" %>
<% end %>

app/views/products/_search.html.erb
<%= form_tag products_path, method: :get, authentication: false , id: "search-form" do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

app/views/products/_show_product.html.erb
<p>Product: <%= @product.name %></p>
<p>Price: $ <%= @product.formatted_price %></p>
<p>Description: <%= @product.description %></p>
<em>Posted by: <%= @product.seller.username %></em>
<% if current_user && !current_user.merchandise.exists?(@product) %>
  <p><%= link_to "Add to Cart", add_to_cart_product_path %></p>
<% end %>

<div>
  <% if current_user == @product.seller %>
    <%= link_to 'Edit', edit_product_path(@product) %>
    <%= link_to 'Delete', product_path(@product), method: :delete, data: {confirm: 'Are you sure?'} %>
  <% end %>
  <%= link_to 'Back', :back %>
</div>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

<%= button_to 'Back', products_path, method: :get %>

app/views/products/index.html.erb
<h1>Products</h1>

<div>
  <%= link_to "New Product", new_product_path %><br><br>
</div>

<div>
  <%= render 'search' %>
</div>

<table id="products">
  <tr>
    <%= render @products %>
  </tr>
</table>

<div class="pagination">
  <%= paginate @products %>
</div>

app/views/products/index.js.erb
$('#products').append('<tr><%= j(render @products) %></tr>'); // appends new products to what is already shown instead of replacing with *html*
$('.pagination').replaceWith('<%= j(paginate @products) %>');

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= button_to 'Back', products_path, method: :get %>

app/views/products/show.html.erb
<h1>Product</h1>

<%= render 'show_product' %>

<h3>Reviews for <%= @product.name %></h3>

<div id="reviews">
  <%= render @reviews %>
</div>

<% if current_user %>
  <%= render 'review_form' %>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p>
<% end %>